### ISSUE TITLE
Consider adding script parameter aliases for BdvHandle and RealTransform

### ISSUE THREAD

**Issue by imagejan** [BIOP/bigdataviewer_scijava#6]
By adding aliases to the scriptService:

```
scriptService.addAlias(BdvHandle.class)
scriptService.addAlias(RealTransform.class)
```

... defining script parameters gets a bit easier, because you can leave away the package name:

```
#@ BdvHandle bdvHandle
#@ RealTransform transform
```

---

This can be done e.g. in the `initialize()` method of a service, like here:

https://github.com/imagej/imagej-common/blob/4ea9f1cf30469806da2947175fb519d41c733e14/src/main/java/net/imagej/display/DefaultImageDisplayService.java#L156-L163

**Comment by NicoKiaru** [comment]
Thanks! Does it mean that I need to create a 'dummy' scriptservice to add these aliases ?

**Comment by imagejan** [comment]
They can be added by anything that runs *once* upon startup. But yes, if you don't have an own `BDVSciJavaService` yet, you could create a "dummy" one (not a `ScriptService` though, but just a new `Service` plugin).

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
